name: API CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'API/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API/requirements.txt

    - name: Run tests (placeholder)
      run: |
        python -c "from API.api_server import app"

    - name: Build (placeholder)
      run: |
        echo "Build step complete."

    - name: Trigger Render Deployment
      if: success()
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
